server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.php index.html;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_read_timeout 300;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    location ~ ^/(\.git|cache|bin|logs|backup|webserver-configs|tmp)/ {
        return 403;
    }
    location ~ /\.ht   { deny all; }
    location ~ /\.git  { deny all; }
    location ~ /\.env  { deny all; }
    location ~ \.yaml$ { deny all; }
    location ~ \.twig$ { deny all; }
    location ~ \.md$   { deny all; }

    location ~* \.(ico|css|js|gif|jpg|jpeg|png|svg|woff|woff2|ttf|eot|webp)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    client_max_body_size 32M;
}